apiVersion: v1
kind: Config

users:
  - name: dev
  - name: client

contexts:
  - name: admin
    context:
      user: dev
      namespace:
        - dev
        - prod

  - name: client
    context:
      user: client
      namespace: prod
