apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-db
  name: redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis-db
    spec:
      containers:
        - image: redis:alpine
          name: redis-db
          resources: {}
      restartPolicy: Always
status: {}
