apiVersion: v1
kind: Ingress
metadata:
  name: redis-db
spec:
  tls:
  - secretName: let-sencrypt-prod
    hosts: 
    - redis-dev.domain.com
  rules:
  - hosts: redis-dev.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName:  redis-svc
          servicePort: 6379